-- active-theme.lua
-- Generated by gen-vim-theme — do not edit directly.
-- Regenerate with: gen-vim-theme

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "active-theme"

local hi = vim.api.nvim_set_hl

-- ── Editor scaffolding ──────────────────────────────────────────────────────
hi(0, "Normal", { fg = "#eceeed", bg = "#101211" })
hi(0, "NormalNC", { fg = "#adb5b2", bg = "#101211" })
hi(0, "NormalFloat", { fg = "#adb5b2", bg = "#202221" })
hi(0, "FloatBorder", { fg = "#373b39", bg = "#202221" })
hi(0, "LineNr", { fg = "#444947" })
hi(0, "CursorLine", { bg = "#202221" })
hi(0, "CursorLineNr", { fg = "#0bd8b6", bg = "#202221" })
hi(0, "ColorColumn", { bg = "#202221" })
hi(0, "SignColumn", { fg = "#444947", bg = "#101211" })
hi(0, "VertSplit", { fg = "#2e3130", bg = "#101211" })
hi(0, "WinSeparator", { fg = "#2e3130", bg = "#101211" })
hi(0, "Folded", { fg = "#63706b", bg = "#202221" })
hi(0, "FoldColumn", { fg = "#444947", bg = "#101211" })
hi(0, "EndOfBuffer", { fg = "#272a29" })
hi(0, "NonText", { fg = "#373b39" })
hi(0, "SpecialKey", { fg = "#5b625f" })
hi(0, "Conceal", { fg = "#5b625f" })

-- ── Selection / search ─────────────────────────────────────────────────────
hi(0, "Visual", { bg = "#023b37" })
hi(0, "VisualNOS", { bg = "#0d2d2a" })
hi(0, "Search", { fg = "#ffca16", bg = "#302008" })
hi(0, "IncSearch", { fg = "#101211", bg = "#ffc53d" })
hi(0, "CurSearch", { fg = "#101211", bg = "#ffc53d" })
hi(0, "MatchParen", { fg = "#0bd8b6", bg = "#2e3130" })
hi(0, "Substitute", { fg = "#eceeed", bg = "#e54666" })

-- ── Status / tabs / menus ──────────────────────────────────────────────────
hi(0, "StatusLine", { fg = "#adb5b2", bg = "#202221" })
hi(0, "StatusLineNC", { fg = "#444947", bg = "#171918" })
hi(0, "TabLine", { fg = "#5b625f", bg = "#171918" })
hi(0, "TabLineSel", { fg = "#0bd8b6", bg = "#0d2d2a" })
hi(0, "TabLineFill", { bg = "#101211" })
hi(0, "WildMenu", { fg = "#adf0dd", bg = "#084843" })

-- ── Popup menu ─────────────────────────────────────────────────────────────
hi(0, "Pmenu", { fg = "#adb5b2", bg = "#202221" })
hi(0, "PmenuSel", { fg = "#adf0dd", bg = "#145750" })
hi(0, "PmenuSbar", { bg = "#272a29" })
hi(0, "PmenuThumb", { bg = "#5b625f" })

-- ── Messages / prompts ─────────────────────────────────────────────────────
hi(0, "ModeMsg", { fg = "#0bd8b6", bold = true })
hi(0, "MoreMsg", { fg = "#3dd68c" })
hi(0, "Question", { fg = "#3dd68c" })
hi(0, "WarningMsg", { fg = "#ffca16" })
hi(0, "ErrorMsg", { fg = "#ff949d", bg = "#3a141e" })
hi(0, "Directory", { fg = "#75c7f0" })
hi(0, "Title", { fg = "#0bd8b6", bold = true })

-- ── Spell ──────────────────────────────────────────────────────────────────
hi(0, "SpellBad", { sp = "#e54666", undercurl = true })
hi(0, "SpellCap", { sp = "#ffc53d", undercurl = true })
hi(0, "SpellRare", { sp = "#7ce2fe", undercurl = true })
hi(0, "SpellLocal", { sp = "#30a46c", undercurl = true })

-- ── Syntax ─────────────────────────────────────────────────────────────────
hi(0, "Comment", { fg = "#5b625f", italic = true })
hi(0, "SpecialComment", { fg = "#63706b", italic = true })

-- Constants / literals
hi(0, "Constant", { fg = "#0bd8b6" })
hi(0, "String", { fg = "#3dd68c" })
hi(0, "Character", { fg = "#3dd68c" })
hi(0, "Number", { fg = "#0bd8b6" })
hi(0, "Float", { fg = "#0bd8b6" })
hi(0, "Boolean", { fg = "#12a594" })

-- Identifiers
hi(0, "Identifier", { fg = "#75c7f0" })
hi(0, "Function", { fg = "#75c7f0" })

-- Control flow keywords
hi(0, "Statement", { fg = "#ff949d" })
hi(0, "Conditional", { fg = "#ff949d" })
hi(0, "Repeat", { fg = "#ff949d" })
hi(0, "Label", { fg = "#ff949d" })
hi(0, "Keyword", { fg = "#ff949d" })
hi(0, "Exception", { fg = "#ff949d" })
hi(0, "Operator", { fg = "#adb5b2" })
hi(0, "Delimiter", { fg = "#717d79" })

-- Preprocessor
hi(0, "PreProc", { fg = "#0eb39e" })
hi(0, "Include", { fg = "#0eb39e" })
hi(0, "Define", { fg = "#0eb39e" })
hi(0, "Macro", { fg = "#0eb39e" })
hi(0, "PreCondit", { fg = "#0eb39e" })

-- Types
hi(0, "Type", { fg = "#ffca16" })
hi(0, "StorageClass", { fg = "#ffca16" })
hi(0, "Structure", { fg = "#ffca16" })
hi(0, "Typedef", { fg = "#ffca16" })

-- Specials
hi(0, "Special", { fg = "#ffc53d" })
hi(0, "SpecialChar", { fg = "#ffc53d" })
hi(0, "Tag", { fg = "#75c7f0" })
hi(0, "Debug", { fg = "#ff949d" })
hi(0, "Underlined", { underline = true })
hi(0, "Ignore", { fg = "#373b39" })
hi(0, "Error", { fg = "#ff949d", bg = "#3a141e" })
hi(0, "Todo", { fg = "#ffca16", bg = "#302008", bold = true })

-- ── Diff ───────────────────────────────────────────────────────────────────
hi(0, "DiffAdd", { fg = "#3dd68c", bg = "#132d21" })
hi(0, "DiffDelete", { fg = "#ff949d", bg = "#3a141e" })
hi(0, "DiffChange", { fg = "#75c7f0", bg = "#112840" })
hi(0, "DiffText", { fg = "#ffca16", bg = "#302008" })

-- ── LSP diagnostics ────────────────────────────────────────────────────────
hi(0, "DiagnosticError", { fg = "#e54666" })
hi(0, "DiagnosticWarn", { fg = "#ffc53d" })
hi(0, "DiagnosticInfo", { fg = "#7ce2fe" })
hi(0, "DiagnosticHint", { fg = "#30a46c" })
hi(0, "DiagnosticUnderlineError", { sp = "#e54666", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ffc53d", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#7ce2fe", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#30a46c", undercurl = true })

-- ── Git signs ──────────────────────────────────────────────────────────────
hi(0, "GitSignsAdd", { fg = "#30a46c" })
hi(0, "GitSignsChange", { fg = "#7ce2fe" })
hi(0, "GitSignsDelete", { fg = "#e54666" })
hi(0, "GitGutterAdd", { link = "GitSignsAdd" })
hi(0, "GitGutterChange", { link = "GitSignsChange" })
hi(0, "GitGutterDelete", { link = "GitSignsDelete" })

-- ── Treesitter semantic tokens ─────────────────────────────────────────────
hi(0, "@variable", { link = "Identifier" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@constant", { link = "Constant" })
hi(0, "@constant.builtin", { link = "Boolean" })
hi(0, "@string", { link = "String" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@number", { link = "Number" })
hi(0, "@boolean", { link = "Boolean" })
hi(0, "@function", { link = "Function" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@method", { link = "Function" })
hi(0, "@parameter", { link = "Identifier" })
hi(0, "@keyword", { link = "Keyword" })
hi(0, "@keyword.operator", { link = "Operator" })
hi(0, "@operator", { link = "Operator" })
hi(0, "@type", { link = "Type" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@include", { link = "Include" })
hi(0, "@comment", { link = "Comment" })
hi(0, "@tag", { link = "Tag" })
hi(0, "@tag.attribute", { link = "Identifier" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.bracket", { link = "Delimiter" })
