" radix.vim
" Generated by gen-vim-theme — do not edit directly.
" Regenerate with: gen-vim-theme

set background=dark
hi clear
if exists("syntax_on") | syntax reset | endif
let g:colors_name = "radix"

" ── Editor scaffolding ──────────────────────────────────────────────────────
hi Normal guifg=#eceeed guibg=#101211 gui=NONE
hi NormalNC guifg=#adb5b2 guibg=#101211 gui=NONE
hi NormalFloat guifg=#adb5b2 guibg=#202221 gui=NONE
hi FloatBorder guifg=#373b39 guibg=#202221 gui=NONE
hi LineNr guifg=#444947 guibg=NONE gui=NONE
hi CursorLine guifg=NONE guibg=#202221 gui=NONE
hi CursorLineNr guifg=#0bd8b6 guibg=#202221 gui=NONE
hi ColorColumn guifg=NONE guibg=#202221 gui=NONE
hi SignColumn guifg=#444947 guibg=#101211 gui=NONE
hi VertSplit guifg=#2e3130 guibg=#101211 gui=NONE
hi WinSeparator guifg=#2e3130 guibg=#101211 gui=NONE
hi Folded guifg=#63706b guibg=#202221 gui=NONE
hi FoldColumn guifg=#444947 guibg=#101211 gui=NONE
hi EndOfBuffer guifg=#272a29 guibg=NONE gui=NONE
hi NonText guifg=#373b39 guibg=NONE gui=NONE
hi SpecialKey guifg=#5b625f guibg=NONE gui=NONE
hi Conceal guifg=#5b625f guibg=NONE gui=NONE

" ── Selection / search ─────────────────────────────────────────────────────
hi Visual guifg=NONE guibg=#023b37 gui=NONE
hi VisualNOS guifg=NONE guibg=#0d2d2a gui=NONE
hi Search guifg=#ffca16 guibg=#302008 gui=NONE
hi IncSearch guifg=#101211 guibg=#ffc53d gui=NONE
hi CurSearch guifg=#101211 guibg=#ffc53d gui=NONE
hi MatchParen guifg=#0bd8b6 guibg=#2e3130 gui=NONE
hi Substitute guifg=#eceeed guibg=#e54666 gui=NONE

" ── Status / tabs / menus ──────────────────────────────────────────────────
hi StatusLine guifg=#adb5b2 guibg=#202221 gui=NONE
hi StatusLineNC guifg=#444947 guibg=#171918 gui=NONE
hi TabLine guifg=#5b625f guibg=#171918 gui=NONE
hi TabLineSel guifg=#0bd8b6 guibg=#0d2d2a gui=NONE
hi TabLineFill guifg=NONE guibg=#101211 gui=NONE
hi WildMenu guifg=#adf0dd guibg=#084843 gui=NONE

" ── Popup menu ─────────────────────────────────────────────────────────────
hi Pmenu guifg=#adb5b2 guibg=#202221 gui=NONE
hi PmenuSel guifg=#adf0dd guibg=#145750 gui=NONE
hi PmenuSbar guifg=NONE guibg=#272a29 gui=NONE
hi PmenuThumb guifg=NONE guibg=#5b625f gui=NONE

" ── Messages / prompts ─────────────────────────────────────────────────────
hi ModeMsg guifg=#0bd8b6 guibg=NONE gui=bold
hi MoreMsg guifg=#3dd68c guibg=NONE gui=NONE
hi Question guifg=#3dd68c guibg=NONE gui=NONE
hi WarningMsg guifg=#ffca16 guibg=NONE gui=NONE
hi ErrorMsg guifg=#ff949d guibg=#3a141e gui=NONE
hi Directory guifg=#75c7f0 guibg=NONE gui=NONE
hi Title guifg=#0bd8b6 guibg=NONE gui=bold

" ── Spell ──────────────────────────────────────────────────────────────────
hi SpellBad   gui=undercurl guisp=#e54666   guifg=NONE guibg=NONE
hi SpellCap   gui=undercurl guisp=#ffc53d guifg=NONE guibg=NONE
hi SpellRare  gui=undercurl guisp=#7ce2fe    guifg=NONE guibg=NONE
hi SpellLocal gui=undercurl guisp=#30a46c guifg=NONE guibg=NONE

" ── Syntax ─────────────────────────────────────────────────────────────────
hi Comment guifg=#5b625f guibg=NONE gui=italic
hi SpecialComment guifg=#63706b guibg=NONE gui=italic

  " Constants / literals
hi Constant guifg=#0bd8b6 guibg=NONE gui=NONE
hi String guifg=#3dd68c guibg=NONE gui=NONE
hi Character guifg=#3dd68c guibg=NONE gui=NONE
hi Number guifg=#0bd8b6 guibg=NONE gui=NONE
hi Float guifg=#0bd8b6 guibg=NONE gui=NONE
hi Boolean guifg=#12a594 guibg=NONE gui=NONE

  " Identifiers
hi Identifier guifg=#75c7f0 guibg=NONE gui=NONE
hi Function guifg=#75c7f0 guibg=NONE gui=NONE

  " Control flow keywords
hi Statement guifg=#ff949d guibg=NONE gui=NONE
hi Conditional guifg=#ff949d guibg=NONE gui=NONE
hi Repeat guifg=#ff949d guibg=NONE gui=NONE
hi Label guifg=#ff949d guibg=NONE gui=NONE
hi Keyword guifg=#ff949d guibg=NONE gui=NONE
hi Exception guifg=#ff949d guibg=NONE gui=NONE
hi Operator guifg=#adb5b2 guibg=NONE gui=NONE
hi Delimiter guifg=#717d79 guibg=NONE gui=NONE

  " Preprocessor
hi PreProc guifg=#0eb39e guibg=NONE gui=NONE
hi Include guifg=#0eb39e guibg=NONE gui=NONE
hi Define guifg=#0eb39e guibg=NONE gui=NONE
hi Macro guifg=#0eb39e guibg=NONE gui=NONE
hi PreCondit guifg=#0eb39e guibg=NONE gui=NONE

  " Types
hi Type guifg=#ffca16 guibg=NONE gui=NONE
hi StorageClass guifg=#ffca16 guibg=NONE gui=NONE
hi Structure guifg=#ffca16 guibg=NONE gui=NONE
hi Typedef guifg=#ffca16 guibg=NONE gui=NONE

  " Specials
hi Special guifg=#ffc53d guibg=NONE gui=NONE
hi SpecialChar guifg=#ffc53d guibg=NONE gui=NONE
hi Tag guifg=#75c7f0 guibg=NONE gui=NONE
hi Debug guifg=#ff949d guibg=NONE gui=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline
hi Ignore guifg=#373b39 guibg=NONE gui=NONE
hi Error guifg=#ff949d guibg=#3a141e gui=NONE
hi Todo guifg=#ffca16 guibg=#302008 gui=bold

" ── Diff ───────────────────────────────────────────────────────────────────
hi DiffAdd guifg=#3dd68c guibg=#132d21 gui=NONE
hi DiffDelete guifg=#ff949d guibg=#3a141e gui=NONE
hi DiffChange guifg=#75c7f0 guibg=#112840 gui=NONE
hi DiffText guifg=#ffca16 guibg=#302008 gui=NONE

" ── LSP diagnostics ────────────────────────────────────────────────────────
hi DiagnosticError guifg=#e54666 guibg=NONE gui=NONE
hi DiagnosticWarn guifg=#ffc53d guibg=NONE gui=NONE
hi DiagnosticInfo guifg=#7ce2fe guibg=NONE gui=NONE
hi DiagnosticHint guifg=#30a46c guibg=NONE gui=NONE
hi DiagnosticUnderlineError gui=undercurl guisp=#e54666   guifg=NONE guibg=NONE
hi DiagnosticUnderlineWarn  gui=undercurl guisp=#ffc53d guifg=NONE guibg=NONE
hi DiagnosticUnderlineInfo  gui=undercurl guisp=#7ce2fe    guifg=NONE guibg=NONE
hi DiagnosticUnderlineHint  gui=undercurl guisp=#30a46c guifg=NONE guibg=NONE

" ── Git signs (vim-gitgutter / gitsigns.nvim) ──────────────────────────────
hi GitSignsAdd guifg=#30a46c guibg=NONE gui=NONE
hi GitSignsChange guifg=#7ce2fe guibg=NONE gui=NONE
hi GitSignsDelete guifg=#e54666 guibg=NONE gui=NONE
hi! link GitGutterAdd GitSignsAdd
hi! link GitGutterChange GitSignsChange
hi! link GitGutterDelete GitSignsDelete

" ── Treesitter semantic tokens (neovim) ────────────────────────────────────
hi! link @variable Identifier
hi! link @variable.builtin Special
hi! link @constant Constant
hi! link @constant.builtin Boolean
hi! link @string String
hi! link @string.escape SpecialChar
hi! link @number Number
hi! link @boolean Boolean
hi! link @function Function
hi! link @function.builtin Special
hi! link @method Function
hi! link @parameter Identifier
hi! link @keyword Keyword
hi! link @keyword.operator Operator
hi! link @operator Operator
hi! link @type Type
hi! link @type.builtin Type
hi! link @namespace Include
hi! link @include Include
hi! link @comment Comment
hi! link @tag Tag
hi! link @tag.attribute Identifier
hi! link @tag.delimiter Delimiter
hi! link @punctuation.delimiter Delimiter
hi! link @punctuation.bracket Delimiter
