#!/usr/bin/env bash

# Path to your Oh My Zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

plugins=(git tmux zsh-ai nvm bun)

# Oh My Zsh :: Node Version Manager (nvm) plugin configuration
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes
zstyle ':omz:plugins:nvm' lazy yes

source $ZSH/oh-my-zsh.sh
source "$DOTFILES/config/zsh/aliases.zsh"
source "$DOTFILES/config/zsh/functions.zsh"

# uv
export PATH="$HOME/.local/bin:$PATH"
# Adds the LM Studio CLI to the PATH
export PATH="$PATH:$HOME/.lmstudio/bin"
# Rust/Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Adds a colored horizontal rule before each command in the terminal
_cmd_rule() {
  local hex="${THEME_GREY_4:-#182449}"
  hex="${hex#\#}"
  local r=$((16#${hex[1,2]})) g=$((16#${hex[3,4]})) b=$((16#${hex[5,6]}))
  printf "\n\e[38;2;${r};${g};${b}m%*s\e[0m\n" "$COLUMNS" '' | tr ' ' '─'
}
add-zsh-hook preexec _cmd_rule

# Add the message of the day (MOTD) to the terminal
clear && motd