font-family = DankMono
font-family-italic = DankMono
window-title-font-family = DankMono
link-url = true
link-previews = true

working-directory = home
window-inherit-working-directory = true
title-report = true
copy-on-select = clipboard
background-opacity = 0.95 
background-blur = true
unfocused-split-opacity = 0.80

macos-icon = custom
theme = active-theme
