#!/usr/bin/env python3
"""
gen-ghostty-theme — generates a Ghostty theme file from the current THEME_* variables.

Reads THEME_* from the environment (set at shell startup by sourcing $DOTFILES/.env).
Falls back to parsing $DOTFILES/.env directly if vars aren't present.

Usage:
  gen-ghostty-theme                   # write to $DOTFILES/config/ghostty/active-theme
  gen-ghostty-theme --stdout          # print to stdout instead
  build-theme --accent violet && gen-ghostty-theme
"""

import os
import sys
import argparse


# ---------------------------------------------------------------------------
# Load theme vars
# ---------------------------------------------------------------------------

def load_theme() -> dict[str, str]:
    """Return THEME_* vars from the environment, parsing $DOTFILES/.env if needed."""
    env = os.environ

    if any(k.startswith("THEME_") for k in env):
        return {k: v for k, v in env.items() if k.startswith("THEME_")}

    dotfiles = env.get("DOTFILES", os.path.expanduser("~/.dotfiles"))
    env_path = os.path.join(dotfiles, ".env")

    theme: dict[str, str] = {}
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line.startswith("THEME_"):
                continue
            key, _, val = line.partition("=")
            theme[key] = val.strip().strip('"').strip("'")
    return theme


# ---------------------------------------------------------------------------
# Theme generation
# ---------------------------------------------------------------------------

def generate(t: dict[str, str]) -> list[str]:
    """Build Ghostty theme config lines from theme vars."""

    def grey(n):    return t[f"THEME_GREY_{n}"]
    def accent(n):  return t[f"THEME_ACCENT_{n}"]
    def error(n):   return t[f"THEME_ERROR_{n}"]
    def warning(n): return t[f"THEME_WARNING_{n}"]
    def success(n): return t[f"THEME_SUCCESS_{n}"]
    def info(n):    return t[f"THEME_INFO_{n}"]

    # THEME_USE_DARK lists roles whose step-9 solid background requires dark foreground
    dark_roles = t.get("THEME_USE_DARK", "").split()
    cursor_text = grey(1) if "accent" in dark_roles else grey(12)

    # Palette mapping:
    #
    # Normal (0-7): step 11 (low-contrast text — readable, slightly muted)
    #   0  black         → GREY_2     (darkest visible background)
    #   1  red           → ERROR_11
    #   2  green         → SUCCESS_11
    #   3  yellow        → WARNING_11
    #   4  blue          → INFO_11
    #   5  magenta       → ACCENT_11  (brand/accent color fills the magenta slot)
    #   6  cyan          → INFO_10    (hover-solid step — adjacent to but distinct from INFO_11 blue)
    #   7  white         → GREY_11
    #
    # Bright (8-15): step 9 (solid — most saturated)
    #   8  bright black  → GREY_7     (visible dark, not pure black)
    #   9  bright red    → ERROR_9
    #  10  bright green  → SUCCESS_9
    #  11  bright yellow → WARNING_9
    #  12  bright blue   → INFO_9
    #  13  bright magenta→ ACCENT_9
    #  14  bright cyan   → INFO_8     (border-hover step — avoids clash with INFO_9 bright blue)
    #  15  bright white  → GREY_12

    lines = [
        "# active-theme",
        "# Generated by gen-ghostty-theme — do not edit directly.",
        "# Regenerate with: gen-ghostty-theme",
        "",
        f"background           = {grey(1)}",
        f"foreground           = {grey(12)}",
        f"selection-background = {accent(5)}",
        f"selection-foreground = {grey(12)}",
        f"cursor-color         = {accent(9)}",
        f"cursor-text          = {cursor_text}",
        "",
        f"palette = 0={grey(2)}",
        f"palette = 1={error(11)}",
        f"palette = 2={success(11)}",
        f"palette = 3={warning(11)}",
        f"palette = 4={info(11)}",
        f"palette = 5={accent(11)}",
        f"palette = 6={info(10)}",
        f"palette = 7={grey(11)}",
        f"palette = 8={grey(7)}",
        f"palette = 9={error(9)}",
        f"palette = 10={success(9)}",
        f"palette = 11={warning(9)}",
        f"palette = 12={info(9)}",
        f"palette = 13={accent(9)}",
        f"palette = 14={info(8)}",
        f"palette = 15={grey(12)}",
    ]

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Ghostty active-theme from current THEME_* vars.")
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of writing to file")
    args = parser.parse_args()

    t = load_theme()
    if not t:
        print("gen-ghostty-theme: error: no THEME_* variables found", file=sys.stderr)
        sys.exit(1)

    lines = generate(t)
    output = "\n".join(lines) + "\n"

    if args.stdout:
        sys.stdout.write(output)
        return

    dotfiles = os.environ.get("DOTFILES", os.path.expanduser("~/.dotfiles"))
    out_path = os.path.join(dotfiles, "config", "ghostty", "active-theme")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w") as f:
        f.write(output)

    print(f"[gen-ghostty-theme] Written to {out_path}")


if __name__ == "__main__":
    main()
