#!/usr/bin/env python3
"""
gen-vim-theme — generates colorschemes from the current THEME_* variables.

Reads THEME_* from the environment (set at shell startup by sourcing $DOTFILES/.env).
Falls back to parsing $DOTFILES/.env directly if vars aren't present.

Outputs:
  $DOTFILES/config/nvim/colors/radix.vim         — VimScript colorscheme
  $DOTFILES/config/nvim/colors/active-theme.lua  — Lua colorscheme

Usage:
  gen-vim-theme                   # write both output files
  gen-vim-theme --stdout          # print to stdout instead
  build-theme --accent violet && gen-vim-theme
"""

import os
import sys
import subprocess
import argparse


# ---------------------------------------------------------------------------
# Load theme vars
# ---------------------------------------------------------------------------

def load_theme() -> dict[str, str]:
    """Return THEME_* vars from the environment, parsing $DOTFILES/.env if needed."""
    env = os.environ

    if any(k.startswith("THEME_") for k in env):
        return {k: v for k, v in env.items() if k.startswith("THEME_")}

    dotfiles = env.get("DOTFILES", os.path.expanduser("~/.dotfiles"))
    env_path = os.path.join(dotfiles, ".env")

    theme: dict[str, str] = {}
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line.startswith("THEME_"):
                continue
            key, _, val = line.partition("=")
            theme[key] = val.strip().strip('"').strip("'")
    return theme


# ---------------------------------------------------------------------------
# Colorscheme generation
# ---------------------------------------------------------------------------

def hi(group: str, fg: str = None, bg: str = None, attrs: list[str] = None) -> str:
    parts = [f"hi {group}"]
    parts.append(f"guifg={fg}" if fg else "guifg=NONE")
    parts.append(f"guibg={bg}" if bg else "guibg=NONE")
    parts.append(f"gui={','.join(attrs)}" if attrs else "gui=NONE")
    return " ".join(parts)


def link(group: str, target: str) -> str:
    return f"hi! link {group} {target}"


def hi_lua(group: str, fg: str = None, bg: str = None, attrs: list[str] = None, sp: str = None) -> str:
    opts: list[str] = []
    if fg:
        opts.append(f'fg = "{fg}"')
    if bg:
        opts.append(f'bg = "{bg}"')
    if sp:
        opts.append(f'sp = "{sp}"')
    for attr in (attrs or []):
        opts.append(f"{attr} = true")
    inner = ", ".join(opts) if opts else ""
    return f'hi(0, "{group}", {{ {inner} }})'


def link_lua(group: str, target: str) -> str:
    return f'hi(0, "{group}", {{ link = "{target}" }})'


def generate(t: dict[str, str]) -> list[str]:
    """Build all highlight commands from theme vars."""

    # Convenience accessors
    def grey(n): return t[f"THEME_GREY_{n}"]
    def accent(n): return t[f"THEME_ACCENT_{n}"]
    def error(n): return t[f"THEME_ERROR_{n}"]
    def warning(n): return t[f"THEME_WARNING_{n}"]
    def success(n): return t[f"THEME_SUCCESS_{n}"]
    def info(n): return t[f"THEME_INFO_{n}"]

    # THEME_USE_DARK lists roles whose step 9/10 bg requires a dark foreground
    dark_roles = t.get("THEME_USE_DARK", "").split()
    def solid_fg(role: str) -> str:
        """Foreground to use on a step-9 solid background for this role."""
        return grey(1) if role in dark_roles else grey(12)

    lines = [
        '" radix.vim',
        '" Generated by gen-vim-theme — do not edit directly.',
        '" Regenerate with: gen-vim-theme',
        '',
        'set background=dark',
        'hi clear',
        'if exists("syntax_on") | syntax reset | endif',
        'let g:colors_name = "radix"',
        '',
        '" ── Editor scaffolding ──────────────────────────────────────────────────────',
        hi("Normal",        fg=grey(12),   bg=grey(1)),
        hi("NormalNC",      fg=grey(11),   bg=grey(1)),
        hi("NormalFloat",   fg=grey(11),   bg=grey(3)),
        hi("FloatBorder",   fg=grey(6),    bg=grey(3)),
        hi("LineNr",        fg=grey(7)),
        hi("CursorLine",    bg=grey(3)),
        hi("CursorLineNr",  fg=accent(11), bg=grey(3)),
        hi("ColorColumn",   bg=grey(3)),
        hi("SignColumn",    fg=grey(7),    bg=grey(1)),
        hi("VertSplit",     fg=grey(5),    bg=grey(1)),
        hi("WinSeparator",  fg=grey(5),    bg=grey(1)),
        hi("Folded",        fg=grey(9),    bg=grey(3)),
        hi("FoldColumn",    fg=grey(7),    bg=grey(1)),
        hi("EndOfBuffer",   fg=grey(4)),
        hi("NonText",       fg=grey(6)),
        hi("SpecialKey",    fg=grey(8)),
        hi("Conceal",       fg=grey(8)),
        '',
        '" ── Selection / search ─────────────────────────────────────────────────────',
        hi("Visual",        bg=accent(4)),
        hi("VisualNOS",     bg=accent(3)),
        hi("Search",        fg=warning(11), bg=warning(3)),
        hi("IncSearch",     fg=solid_fg("warning"), bg=warning(9)),
        hi("CurSearch",     fg=solid_fg("warning"), bg=warning(9)),
        hi("MatchParen",    fg=accent(11), bg=grey(5)),
        hi("Substitute",    fg=solid_fg("error"),   bg=error(9)),
        '',
        '" ── Status / tabs / menus ──────────────────────────────────────────────────',
        hi("StatusLine",    fg=grey(11),   bg=grey(3)),
        hi("StatusLineNC",  fg=grey(7),    bg=grey(2)),
        hi("TabLine",       fg=grey(8),    bg=grey(2)),
        hi("TabLineSel",    fg=accent(11), bg=accent(3)),
        hi("TabLineFill",   bg=grey(1)),
        hi("WildMenu",      fg=accent(12), bg=accent(5)),
        '',
        '" ── Popup menu ─────────────────────────────────────────────────────────────',
        hi("Pmenu",         fg=grey(11),   bg=grey(3)),
        hi("PmenuSel",      fg=accent(12), bg=accent(6)),
        hi("PmenuSbar",     bg=grey(4)),
        hi("PmenuThumb",    bg=grey(8)),
        '',
        '" ── Messages / prompts ─────────────────────────────────────────────────────',
        hi("ModeMsg",       fg=accent(11), attrs=["bold"]),
        hi("MoreMsg",       fg=success(11)),
        hi("Question",      fg=success(11)),
        hi("WarningMsg",    fg=warning(11)),
        hi("ErrorMsg",      fg=error(11),  bg=error(3)),
        hi("Directory",     fg=info(11)),
        hi("Title",         fg=accent(11), attrs=["bold"]),
        '',
        '" ── Spell ──────────────────────────────────────────────────────────────────',
        f"hi SpellBad   gui=undercurl guisp={error(9)}   guifg=NONE guibg=NONE",
        f"hi SpellCap   gui=undercurl guisp={warning(9)} guifg=NONE guibg=NONE",
        f"hi SpellRare  gui=undercurl guisp={info(9)}    guifg=NONE guibg=NONE",
        f"hi SpellLocal gui=undercurl guisp={success(9)} guifg=NONE guibg=NONE",
        '',
        '" ── Syntax ─────────────────────────────────────────────────────────────────',
        hi("Comment",       fg=grey(8),    attrs=["italic"]),
        hi("SpecialComment",fg=grey(9),    attrs=["italic"]),
        '',
        '  " Constants / literals',
        hi("Constant",      fg=accent(11)),
        hi("String",        fg=success(11)),
        hi("Character",     fg=success(11)),
        hi("Number",        fg=accent(11)),
        hi("Float",         fg=accent(11)),
        hi("Boolean",       fg=accent(9)),
        '',
        '  " Identifiers',
        hi("Identifier",    fg=info(11)),
        hi("Function",      fg=info(11)),
        '',
        '  " Control flow keywords',
        hi("Statement",     fg=error(11)),
        hi("Conditional",   fg=error(11)),
        hi("Repeat",        fg=error(11)),
        hi("Label",         fg=error(11)),
        hi("Keyword",       fg=error(11)),
        hi("Exception",     fg=error(11)),
        hi("Operator",      fg=grey(11)),
        hi("Delimiter",     fg=grey(10)),
        '',
        '  " Preprocessor',
        hi("PreProc",       fg=accent(10)),
        hi("Include",       fg=accent(10)),
        hi("Define",        fg=accent(10)),
        hi("Macro",         fg=accent(10)),
        hi("PreCondit",     fg=accent(10)),
        '',
        '  " Types',
        hi("Type",          fg=warning(11)),
        hi("StorageClass",  fg=warning(11)),
        hi("Structure",     fg=warning(11)),
        hi("Typedef",       fg=warning(11)),
        '',
        '  " Specials',
        hi("Special",       fg=warning(9)),
        hi("SpecialChar",   fg=warning(9)),
        hi("Tag",           fg=info(11)),
        hi("Debug",         fg=error(11)),
        hi("Underlined",    attrs=["underline"]),
        hi("Ignore",        fg=grey(6)),
        hi("Error",         fg=error(11),  bg=error(3)),
        hi("Todo",          fg=warning(11), bg=warning(3), attrs=["bold"]),
        '',
        '" ── Diff ───────────────────────────────────────────────────────────────────',
        hi("DiffAdd",       fg=success(11), bg=success(3)),
        hi("DiffDelete",    fg=error(11),   bg=error(3)),
        hi("DiffChange",    fg=info(11),    bg=info(3)),
        hi("DiffText",      fg=warning(11), bg=warning(3)),
        '',
        '" ── LSP diagnostics ────────────────────────────────────────────────────────',
        hi("DiagnosticError",            fg=error(9)),
        hi("DiagnosticWarn",             fg=warning(9)),
        hi("DiagnosticInfo",             fg=info(9)),
        hi("DiagnosticHint",             fg=success(9)),
        f"hi DiagnosticUnderlineError gui=undercurl guisp={error(9)}   guifg=NONE guibg=NONE",
        f"hi DiagnosticUnderlineWarn  gui=undercurl guisp={warning(9)} guifg=NONE guibg=NONE",
        f"hi DiagnosticUnderlineInfo  gui=undercurl guisp={info(9)}    guifg=NONE guibg=NONE",
        f"hi DiagnosticUnderlineHint  gui=undercurl guisp={success(9)} guifg=NONE guibg=NONE",
        '',
        '" ── Git signs (vim-gitgutter / gitsigns.nvim) ──────────────────────────────',
        hi("GitSignsAdd",    fg=success(9)),
        hi("GitSignsChange", fg=info(9)),
        hi("GitSignsDelete", fg=error(9)),
        link("GitGutterAdd",    "GitSignsAdd"),
        link("GitGutterChange", "GitSignsChange"),
        link("GitGutterDelete", "GitSignsDelete"),
        '',
        '" ── Treesitter semantic tokens (neovim) ────────────────────────────────────',
        link("@variable",              "Identifier"),
        link("@variable.builtin",      "Special"),
        link("@constant",              "Constant"),
        link("@constant.builtin",      "Boolean"),
        link("@string",                "String"),
        link("@string.escape",         "SpecialChar"),
        link("@number",                "Number"),
        link("@boolean",               "Boolean"),
        link("@function",              "Function"),
        link("@function.builtin",      "Special"),
        link("@method",                "Function"),
        link("@parameter",             "Identifier"),
        link("@keyword",               "Keyword"),
        link("@keyword.operator",      "Operator"),
        link("@operator",              "Operator"),
        link("@type",                  "Type"),
        link("@type.builtin",          "Type"),
        link("@namespace",             "Include"),
        link("@include",               "Include"),
        link("@comment",               "Comment"),
        link("@tag",                   "Tag"),
        link("@tag.attribute",         "Identifier"),
        link("@tag.delimiter",         "Delimiter"),
        link("@punctuation.delimiter", "Delimiter"),
        link("@punctuation.bracket",   "Delimiter"),
    ]

    return lines


def generate_lua(t: dict[str, str]) -> list[str]:
    """Build a Lua colorscheme (active-theme.lua) from theme vars."""

    def grey(n): return t[f"THEME_GREY_{n}"]
    def accent(n): return t[f"THEME_ACCENT_{n}"]
    def error(n): return t[f"THEME_ERROR_{n}"]
    def warning(n): return t[f"THEME_WARNING_{n}"]
    def success(n): return t[f"THEME_SUCCESS_{n}"]
    def info(n): return t[f"THEME_INFO_{n}"]

    dark_roles = t.get("THEME_USE_DARK", "").split()
    def solid_fg(role: str) -> str:
        return grey(1) if role in dark_roles else grey(12)

    lines = [
        "-- active-theme.lua",
        "-- Generated by gen-vim-theme — do not edit directly.",
        "-- Regenerate with: gen-vim-theme",
        "",
        'vim.cmd("hi clear")',
        'if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end',
        'vim.o.background = "dark"',
        'vim.g.colors_name = "active-theme"',
        "",
        "local hi = vim.api.nvim_set_hl",
        "",
        "-- ── Editor scaffolding ──────────────────────────────────────────────────────",
        hi_lua("Normal",        fg=grey(12),   bg=grey(1)),
        hi_lua("NormalNC",      fg=grey(11),   bg=grey(1)),
        hi_lua("NormalFloat",   fg=grey(11),   bg=grey(3)),
        hi_lua("FloatBorder",   fg=grey(6),    bg=grey(3)),
        hi_lua("LineNr",        fg=grey(7)),
        hi_lua("CursorLine",    bg=grey(3)),
        hi_lua("CursorLineNr",  fg=accent(11), bg=grey(3)),
        hi_lua("ColorColumn",   bg=grey(3)),
        hi_lua("SignColumn",    fg=grey(7),    bg=grey(1)),
        hi_lua("VertSplit",     fg=grey(5),    bg=grey(1)),
        hi_lua("WinSeparator",  fg=grey(5),    bg=grey(1)),
        hi_lua("Folded",        fg=grey(9),    bg=grey(3)),
        hi_lua("FoldColumn",    fg=grey(7),    bg=grey(1)),
        hi_lua("EndOfBuffer",   fg=grey(4)),
        hi_lua("NonText",       fg=grey(6)),
        hi_lua("SpecialKey",    fg=grey(8)),
        hi_lua("Conceal",       fg=grey(8)),
        "",
        "-- ── Selection / search ─────────────────────────────────────────────────────",
        hi_lua("Visual",        bg=accent(4)),
        hi_lua("VisualNOS",     bg=accent(3)),
        hi_lua("Search",        fg=warning(11), bg=warning(3)),
        hi_lua("IncSearch",     fg=solid_fg("warning"), bg=warning(9)),
        hi_lua("CurSearch",     fg=solid_fg("warning"), bg=warning(9)),
        hi_lua("MatchParen",    fg=accent(11), bg=grey(5)),
        hi_lua("Substitute",    fg=solid_fg("error"),   bg=error(9)),
        "",
        "-- ── Status / tabs / menus ──────────────────────────────────────────────────",
        hi_lua("StatusLine",    fg=grey(11),   bg=grey(3)),
        hi_lua("StatusLineNC",  fg=grey(7),    bg=grey(2)),
        hi_lua("TabLine",       fg=grey(8),    bg=grey(2)),
        hi_lua("TabLineSel",    fg=accent(11), bg=accent(3)),
        hi_lua("TabLineFill",   bg=grey(1)),
        hi_lua("WildMenu",      fg=accent(12), bg=accent(5)),
        "",
        "-- ── Popup menu ─────────────────────────────────────────────────────────────",
        hi_lua("Pmenu",         fg=grey(11),   bg=grey(3)),
        hi_lua("PmenuSel",      fg=accent(12), bg=accent(6)),
        hi_lua("PmenuSbar",     bg=grey(4)),
        hi_lua("PmenuThumb",    bg=grey(8)),
        "",
        "-- ── Messages / prompts ─────────────────────────────────────────────────────",
        hi_lua("ModeMsg",       fg=accent(11), attrs=["bold"]),
        hi_lua("MoreMsg",       fg=success(11)),
        hi_lua("Question",      fg=success(11)),
        hi_lua("WarningMsg",    fg=warning(11)),
        hi_lua("ErrorMsg",      fg=error(11),  bg=error(3)),
        hi_lua("Directory",     fg=info(11)),
        hi_lua("Title",         fg=accent(11), attrs=["bold"]),
        "",
        "-- ── Spell ──────────────────────────────────────────────────────────────────",
        hi_lua("SpellBad",   attrs=["undercurl"], sp=error(9)),
        hi_lua("SpellCap",   attrs=["undercurl"], sp=warning(9)),
        hi_lua("SpellRare",  attrs=["undercurl"], sp=info(9)),
        hi_lua("SpellLocal", attrs=["undercurl"], sp=success(9)),
        "",
        "-- ── Syntax ─────────────────────────────────────────────────────────────────",
        hi_lua("Comment",        fg=grey(8),    attrs=["italic"]),
        hi_lua("SpecialComment", fg=grey(9),    attrs=["italic"]),
        "",
        "-- Constants / literals",
        hi_lua("Constant",  fg=accent(11)),
        hi_lua("String",    fg=success(11)),
        hi_lua("Character", fg=success(11)),
        hi_lua("Number",    fg=accent(11)),
        hi_lua("Float",     fg=accent(11)),
        hi_lua("Boolean",   fg=accent(9)),
        "",
        "-- Identifiers",
        hi_lua("Identifier", fg=info(11)),
        hi_lua("Function",   fg=info(11)),
        "",
        "-- Control flow keywords",
        hi_lua("Statement",  fg=error(11)),
        hi_lua("Conditional",fg=error(11)),
        hi_lua("Repeat",     fg=error(11)),
        hi_lua("Label",      fg=error(11)),
        hi_lua("Keyword",    fg=error(11)),
        hi_lua("Exception",  fg=error(11)),
        hi_lua("Operator",   fg=grey(11)),
        hi_lua("Delimiter",  fg=grey(10)),
        "",
        "-- Preprocessor",
        hi_lua("PreProc",   fg=accent(10)),
        hi_lua("Include",   fg=accent(10)),
        hi_lua("Define",    fg=accent(10)),
        hi_lua("Macro",     fg=accent(10)),
        hi_lua("PreCondit", fg=accent(10)),
        "",
        "-- Types",
        hi_lua("Type",         fg=warning(11)),
        hi_lua("StorageClass", fg=warning(11)),
        hi_lua("Structure",    fg=warning(11)),
        hi_lua("Typedef",      fg=warning(11)),
        "",
        "-- Specials",
        hi_lua("Special",     fg=warning(9)),
        hi_lua("SpecialChar", fg=warning(9)),
        hi_lua("Tag",         fg=info(11)),
        hi_lua("Debug",       fg=error(11)),
        hi_lua("Underlined",  attrs=["underline"]),
        hi_lua("Ignore",      fg=grey(6)),
        hi_lua("Error",       fg=error(11),  bg=error(3)),
        hi_lua("Todo",        fg=warning(11), bg=warning(3), attrs=["bold"]),
        "",
        "-- ── Diff ───────────────────────────────────────────────────────────────────",
        hi_lua("DiffAdd",    fg=success(11), bg=success(3)),
        hi_lua("DiffDelete", fg=error(11),   bg=error(3)),
        hi_lua("DiffChange", fg=info(11),    bg=info(3)),
        hi_lua("DiffText",   fg=warning(11), bg=warning(3)),
        "",
        "-- ── LSP diagnostics ────────────────────────────────────────────────────────",
        hi_lua("DiagnosticError", fg=error(9)),
        hi_lua("DiagnosticWarn",  fg=warning(9)),
        hi_lua("DiagnosticInfo",  fg=info(9)),
        hi_lua("DiagnosticHint",  fg=success(9)),
        hi_lua("DiagnosticUnderlineError", attrs=["undercurl"], sp=error(9)),
        hi_lua("DiagnosticUnderlineWarn",  attrs=["undercurl"], sp=warning(9)),
        hi_lua("DiagnosticUnderlineInfo",  attrs=["undercurl"], sp=info(9)),
        hi_lua("DiagnosticUnderlineHint",  attrs=["undercurl"], sp=success(9)),
        "",
        "-- ── Git signs ──────────────────────────────────────────────────────────────",
        hi_lua("GitSignsAdd",    fg=success(9)),
        hi_lua("GitSignsChange", fg=info(9)),
        hi_lua("GitSignsDelete", fg=error(9)),
        link_lua("GitGutterAdd",    "GitSignsAdd"),
        link_lua("GitGutterChange", "GitSignsChange"),
        link_lua("GitGutterDelete", "GitSignsDelete"),
        "",
        "-- ── Treesitter semantic tokens ─────────────────────────────────────────────",
        link_lua("@variable",              "Identifier"),
        link_lua("@variable.builtin",      "Special"),
        link_lua("@constant",              "Constant"),
        link_lua("@constant.builtin",      "Boolean"),
        link_lua("@string",                "String"),
        link_lua("@string.escape",         "SpecialChar"),
        link_lua("@number",                "Number"),
        link_lua("@boolean",               "Boolean"),
        link_lua("@function",              "Function"),
        link_lua("@function.builtin",      "Special"),
        link_lua("@method",                "Function"),
        link_lua("@parameter",             "Identifier"),
        link_lua("@keyword",               "Keyword"),
        link_lua("@keyword.operator",      "Operator"),
        link_lua("@operator",              "Operator"),
        link_lua("@type",                  "Type"),
        link_lua("@type.builtin",          "Type"),
        link_lua("@namespace",             "Include"),
        link_lua("@include",               "Include"),
        link_lua("@comment",               "Comment"),
        link_lua("@tag",                   "Tag"),
        link_lua("@tag.attribute",         "Identifier"),
        link_lua("@tag.delimiter",         "Delimiter"),
        link_lua("@punctuation.delimiter", "Delimiter"),
        link_lua("@punctuation.bracket",   "Delimiter"),
    ]

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate vim/nvim colorschemes from current THEME_* vars.")
    parser.add_argument("--stdout", action="store_true", help="Print vim output to stdout instead of writing files")
    args = parser.parse_args()

    t = load_theme()
    if not t:
        print("gen-vim-theme: error: no THEME_* variables found", file=sys.stderr)
        sys.exit(1)

    vim_output  = "\n".join(generate(t)) + "\n"
    nvim_output = "\n".join(generate_lua(t)) + "\n"

    if args.stdout:
        sys.stdout.write(vim_output)
        return

    dotfiles = os.environ.get("DOTFILES", os.path.expanduser("~/.dotfiles"))

    vim_path = os.path.join(dotfiles, "config", "nvim", "colors", "radix.vim")
    os.makedirs(os.path.dirname(vim_path), exist_ok=True)
    with open(vim_path, "w") as f:
        f.write(vim_output)
    print(f"[gen-vim-theme] Written to {vim_path}")

    nvim_path = os.path.join(dotfiles, "config", "nvim", "colors", "active-theme.lua")
    os.makedirs(os.path.dirname(nvim_path), exist_ok=True)
    with open(nvim_path, "w") as f:
        f.write(nvim_output)
    print(f"[gen-vim-theme] Written to {nvim_path}")


if __name__ == "__main__":
    main()
